export default {
  id: "tinyfish",
  alias: "tinyfish",
  display: {
    name: "TinyFish",
    color: "#FF6700",
    textIcon: "TF",
    website: "https://www.tinyfish.ai/",
    notice: { apiKeyUrl: "https://agent.tinyfish.ai/api-keys" },
  },
  category: "apikey",
  authType: "apikey",
  serviceKinds: ["webSearch", "webFetch"],
  searchConfig: {
    baseUrl: "https://api.search.tinyfish.ai",
    validateUrl: "https://api.search.tinyfish.ai/usage?limit=1",
    method: "GET",
    authType: "apikey",
    authHeader: "x-api-key",
    costPerQuery: 0,
    searchTypes: ["web", "news", "research_paper"],
    defaultMaxResults: 5,
    maxMaxResults: 10,
    timeoutMs: 10000,
  },
  fetchConfig: {
    baseUrl: "https://api.fetch.tinyfish.ai",
    method: "POST",
    authType: "apikey",
    authHeader: "x-api-key",
    costPerQuery: 0,
    formats: ["markdown", "html"],
    maxCharacters: 100000,
    timeoutMs: 150000,
  },
};
